export const config =
  {
    authentication:{
      server:'http://localhost:3003',//http://authentication.lienketthuonghieu.solutions',
      login:'/login',
      logout:'/logout',
      changePassword:'/change_password',
      grantPermission:'/grant_permission'
    },
    database:{
      server:'http://database.lienketthuonghieu.solutions'//'http://localhost:5984/'
    },
    refund:{
      level_0:0,
      level_1:120,
      level_2:110,
      level_3:100,
      level_4:90,
      level_5:80,
      level_6:70,
      level_7:60,
      level_8:50,
      level_9:40,
      level_10:30,
      level_11:20,
      level_12:10,
    },
    directRefund:300
  };
